### ISSUE TITLE
Publish to melpa

### ISSUE THREAD

**Issue by nibon7** [herbertjones/nushell-ts-mode#2]
Hi @herbertjones, would you mind publishing it to [MELPA](https://melpa.org/#/) or [NonGNU](https://savannah.nongnu.org/)?
It would be great to use the built-in package manager in emacs to get this package. :smile:

**Comment by herbertjones** [comment]
Looks like I'll need to separate `nushell-ts-babel` into its own repository first according to: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#what-to-know-before-opening-a-pull-request

**Comment by herbertjones** [comment]
https://github.com/melpa/melpa/pull/8724

**Comment by herbertjones** [comment]
Accepted by Melpa.
